# Generated by Django 5.1 on 2024-09-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_img/')),
            ],
        ),
    ]
