# Generated by Django 5.1 on 2024-09-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='type',
        ),
    ]
