# Generated by Django 5.1 on 2024-09-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='preferred_loc',
            new_name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget',
        ),
    ]
